logging_config_path: "configs/data_gen_logging_config.yaml" # logging_config_path or "default"

random_state: -1 # if you don't want to specify a random seed, put -1 in this field
ds_size: 150
output_img_path: "draft_img"
output_mask_path: "draft_mask"
sub_datasets_size: 
  - 0.33
  - 0.33
  - 0.33

sub_datasets_config_path:
  - "configs/ds_type_01_500-01.yaml"
  - "configs/ds_type_02_500-01.yaml"
  - "configs/ds_type_03_500-01.yaml"
