version: 1

consol_log:
  level: INFO

formatters:
  simple:
    class: logging.Formatter
    format: "%(asctime)s %(name)s %(levelname)s %(message)s"
    datefmt: "%Y-%m-%d %H:%M:%S"

handlers:
  log_handler_debug:
    class: logging.FileHandler
    filename: logs/data_gen_debug.log
    level: DEBUG
    formatter: simple

  log_handler_info:
    class: logging.FileHandler
    filename: logs/data_gen_info.log
    level: INFO
    formatter: simple

  stream_handler:
    class: logging.StreamHandler
    stream: ext://sys.stderr
    level: cfg://consol_log.level
    formatter: simple

loggers:
  data_gen:
    level: DEBUG
    handlers: [log_handler_debug, log_handler_info, stream_handler]
    propagate: no

