img_size: [400, 400]
img_name_prefix: "sub_ds_3"
noise_pipeline: [

  ["add_grad", {prob: 0.5, min_c: 0.01, max_c: 0.2, direction: "horizontal"}],
  ["add_grad", {prob: 0.5, min_c: 0.01, max_c: 0.2, direction: "vertical"}],
  ["add_grad", {prob: 0.5, min_c: 0.01, max_c: 0.2, direction: "diagonal"}],
  ["img_rotation", {prob: 0.5, scale: True}],
  ["add_grad", {prob: 0.4, min_c: 0.01, max_c: 0.2, direction: "horizontal"}],
  ["add_grad", {prob: 0.4, min_c: 0.01, max_c: 0.2, direction: "vertical"}],
  ["add_grad", {prob: 0.4, min_c: 0.01, max_c: 0.2, direction: "diagonal"}],
  ["img_rotation", {prob: 0.4, scale: True}],
  ["add_grad", {prob: 0.3, min_c: 0.01, max_c: 0.1, direction: "horizontal"}],
  ["add_grad", {prob: 0.3, min_c: 0.01, max_c: 0.1, direction: "vertical"}],
  ["add_grad", {prob: 0.3, min_c: 0.01, max_c: 0.1, direction: "diagonal"}],
  ["img_rotation", {prob: 0.3, scale: True}],
  ["add_rand_lines", {
    p_deflection_min_max: [0.1, 0.4], 
    p_momentum_min_max: [0.7, 0.95],
    pattern_shift_per_row_min_max: [0.01, 0.2],
    p_pattern_min_max: [0.6, 0.95],
    p_rupture_min_max: [0.01, 0.05],
    p_continuation_min_max: [0.03, 0.1],
    num_lines_min_max: [1, 3],
    thickness_min_max: [40, 70],
    dist_between_min_max: [10, 50],
    color_min_max: [0.1, 0.4]
  }]
]

mask_pipeline: [
  ["add_rand_lines", {
    p_deflection_min_max: [0.1, 0.4], 
    p_momentum_min_max: [0.7, 0.95],
    pattern_shift_per_row_min_max: [0.01, 0.2],
    p_pattern_min_max: [0.6, 0.95],
    p_rupture_min_max: [0.01, 0.05],
    p_continuation_min_max: [0.03, 0.1],
    num_lines_min_max: [5, 70],
    thickness_min_max: [3, 20],
    dist_between_min_max: [10, 50],
    color_min_max: [0.1, 0.4]
  }]
]