img_size: [200, 200]
img_name_prefix: "sub_ds_2"
noise_pipeline: [
  ["add_grad", {prob: 0.9, min_c: 0.1, max_c: 0.3, direction: "diagonal"}],
  ["add_grad", {prob: 0.9, min_c: 0.1, max_c: 0.3, direction: "diagonal"}],
  ["img_rotation", {prob: 0.9}],
  ["add_grad", {prob: 0.9, min_c: 0.1, max_c: 0.3, direction: "diagonal"}]
]

mask_pipeline: [
  ["add_rand_lines", {
    p_deflection_min_max: [0.1, 0.9], 
    p_momentum_min_max: [0.1, 0.9],
    pattern_shift_per_row_min_max: [0.01, 0.2],
    p_pattern_min_max: [0.1, 0.9],
    p_rupture_min_max: [0.1, 0.9],
    p_continuation_min_max: [0.1, 0.9],
    num_lines_min_max: [1, 20],
    thickness_min_max: [1, 20],
    dist_between_min_max: [1, 20],
    color_min_max: [0.1, 0.4]
  }]
]